
trigger:
- master

pool:
  vmImage: 'macos-latest'

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'MapsSDKExamplesSwift'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'MapsSDKExamples.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
