
trigger:
- master

pool:
  vmImage: 'macos-latest'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '#!/bin/bash
      gem install fastlane -NV'

steps:
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'MapsSDKExamplesSwift'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'MapsSDKExamples.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
